1: 
  description: "This is the first stage"
  deployments:
    project_core:
      parameters:
        project_code: "101"
        service_tier: "nonp"
    org_service_controls:
      parameters:
        service_tier: "nonp"
2: 
  description: "This is the second stage"
  deployments:
    secrets:
      parameters:
        service_tier: "nonp"
        project_code: "006"
